### PR TITLE
Windows build fixes

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by bmagyar** [comment]
Are you seeing an actual problem with this, e.g. a picky compiler, or it's personal preference?

**Comment by Tobias-Fischer** [comment]
I'm trying to compile this package on Windows for https://github.com/RoboStack/ros-noetic. I noticed that there are more non-standard usages, I'll fix it tomorrow and update the PR.

**Comment by Tobias-Fischer** [comment]
Okay, all issues are fixed now. twist-mux can now be compiled for Windows - see https://github.com/RoboStack/ros-noetic :)

**Comment by bmagyar** [comment]
Sad to see this tbh. These alternative operators are part of the standard, apparently not all compilers implement the full standard.

**Comment by Tobias-Fischer** [comment]
Thanks for merging! I didn't realize it's part of the standard. Potentially including iso646.h (https://docs.microsoft.com/en-us/cpp/c-runtime-library/iso646-operators?view=msvc-160) could have helped.

**Pull request merged**
