### PR TITLE
Foxy updates

### PR DESCRIPTION
**Pull request by v-lopez**
Added some arguments and updates for foxy on top of https://github.com/ros-teleop/twist_mux/pull/18

We may want a foxy branch instead of merging to dashing.

### CODE REVIEW

**Comment by bmagyar** [comment]
I've retargeted to foxy-devel.
Are these commits accurate? Are you sure you wanted to include all?

**Comment by v-lopez** [comment]
I branched off #18 and added my thing, I did some super basic test and it works. (ie publishing on one topic and it being republished to other topic).

**Comment by v-lopez** [comment]
I disabled the test that was failing (test needs migration still) but the code works fine, tested multiple topics with different priorities and joystick priority.
Also fixed a segfault when closing and some valgrind complains.
Updated format and licenses. Should be good to go.

**Comment by bmagyar** [comment]
Thank you!

**Pull request merged**
