### PR TITLE
[ROS1] Fix tests for Python3

### PR DESCRIPTION
**Pull request by wxmerkt**
@bmagyar: Follow-up to #39 -- I noticed I hadn't run the tests and the other PR did not run CI yet. This should fix the tests for both Melodic and Noetic without having to branch unnecessarily

### CODE REVIEW

**Review by bmagyar — APPROVED** [review]
looks legit!

**Comment by wxmerkt** [comment]
Awesome, thank you. Can you please run a patch release to Noetic? Thank you :-)

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/35038

**Comment by wxmerkt** [comment]
Thank you :-)

**Comment by bmagyar** [comment]
No problem!

**Pull request merged**
